FROM php:8.3.0 as php

RUN apt-get update -y
RUN apt-get install -y unzip libpq-dev libcurl4-gnutls-dev
RUN docker-php-ext-install pdo pdo_mysql   #bc math
RUN pecl install -o -f redis && rm -rf /tmp/pear && docker-php-ext-enable redis
RUN pecl install --force apfd && rm -rf /tmp/pear && docker-php-ext-enable apfd

COPY --from=composer:2.3.5 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/app
COPY . .
RUN chmod a+x docker/entrypoint.sh

ENTRYPOINT [ "docker/entrypoint.sh" ]

