#version: '3'
services:
  web:
    image: 'nginx:latest'
    ports:
      - '8003:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./FE_API_Eindopdracht:/var/www/html
    depends_on:
      - worker
    networks:
      - laravel
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: api_eind
      MYSQL_ROOT_PASSWORD: secret
      #MYSQL_USER:
      #MYSQL_PASSWORD: secret
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - '33306:3306'
#  redis:
#    image: 'redis:latest'
#    networks:
#      - laravel
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - '8000:9000'
    networks:
      - laravel
#Networks
networks:
  laravel:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
